kiwicom/universal-components

.eslintignore
README.md
package.json

- No need of .eslintignore and I think the less files the better

Add Android on README and remove .eslintignore

---

.gitignore
package.json
scripts/createPackage.js
src/index.js
yarn.lock

Move dependencies to devDependencies

Add whitelisting of files and folders, copy files from src to lib

---

.circleci/config.yml
package.json

Setup Circleci

---

.storybook/addons.js
.storybook/webpack.config.js
package.json
src/Button/AccessibilityTypes.js
src/Button/Button.stories.js
src/Button/ButtonTitle.js
src/Button/ButtonTypes.js
src/Button/GenericButtonWrapper.js
src/Button/Touchable.js
src/Button/index.js
src/Button/styles/index.native.js
src/Button/styles/index.web.js
src/Button/styles/shared.js
src/Text/index.js
src/index.js
src/native/Icon/index.js
storybook.native/addons.js
storybook.native/rn-addons.js
storybook.native/story-loader.js
yarn.lock

Button component

---

.storybook/preview-head.html

Added font smoothing style to Storybook head to have consistent rendering with `orbit-components` (where this style is added by `chaptersAddon`)
**Before:**
**After:**

Enhance: Storybook font smoothing

---

src/Button/ButtonTitle.js
src/Button/Touchable.js
src/Button/index.js
src/FormFeedback/index.js
src/Icon/IconsList.js
src/ServiceLogo/component/index.native.js
src/ServiceLogo/component/index.web.js
src/Text/TextTypes.js
src/Text/index.js
src/TextInput/FormLabel.js
src/TextInput/__tests__/__snapshots__/index.test.js.snap
src/TextInput/index.js

Use our Text component

---

src/FilterButton/FilterButton.stories.js
src/FilterButton/FilterButtonTypes.js
src/FilterButton/__tests__/__snapshots__/index.test.js.snap
src/FilterButton/__tests__/index.test.js
src/FilterButton/index.js
storybook.native/story-loader.js

Filter Button 

---

src/Rating/Rating.js
src/Rating/Rating.stories.js
src/Rating/__tests__/__snapshots__/index.test.js.snap
src/Rating/__tests__/index.test.js
src/Rating/index.js

Add: Rating component

---

.gitignore
src/CarrierLogo/CarrierLogo.js
src/CarrierLogo/CarrierLogo.stories.js
src/CarrierLogo/CarrierLogoHelpers.js
src/CarrierLogo/CarrierLogoTypes.js
src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
src/CarrierLogo/__tests__/index.test.js
src/CarrierLogo/consts.js
src/CarrierLogo/index.js
src/CarrierLogo/styles/index.js

Add: CarrierLogo component

---

.gitignore
README.md
package.json
scripts/createPackage.js
src/index.js

- updated package name
- added few missing components to `src/index.js`
- small update to `scripts/createPackage.js` because it kept crashing on nested sub-folders during copy (for example in cases like `src/ServiceLogo/assets/GrayJCBLogo.imageset`)

Enhance: Module setup

---

.release-it.json
package.json
scripts/package.json
src/Icon/Icon.web.js
yarn.lock

Fixes #109, fixes #110 and fixes #111.

Fix lib issues

---

__tests__/build.test.js

Add unit test for build process

---

package.json
src/Accordion/Accordion.js
src/Accordion/Accordion.stories.js
src/Accordion/__tests__/index.test.js
src/Accordion/index.js
src/index.js
yarn.lock

Summary: This component makes it possible to toggle a card to display some content; primary use will be to create the TimelineFlightDetail component in margarita (which is currently a blocked PR in this repo).

Feat: Added Accordion component

---

package.json
src/Checkbox/Hoverable.js
src/DatePicker/DatePicker.ios.js
src/DatePicker/DatePicker.stories.js
src/DatePicker/DatePicker.web.js
src/DatePicker/DatePickerDayTile.js
src/DatePicker/DatePickerHelpers.js
src/DatePicker/DatePickerTypes.js
src/DatePicker/__tests__/index.test.js
yarn.lock

Summary: Removed `react-datepicker` dependency which complicated implementation of component in `margarita`.
Replaced web component version with basic date picker implementation, which is closer to current mobile versions.
Small updates to iOS version to keep behavior consistent.

Feat: Updated DatePicker

---

src/index.js

Summary: This component was meant to be more of an internal tool to create buttons, etc. but other components might need to deal with onPress events too.

Fix: Exported Touchable component

---

src/Badge/Badge.js

Default font size in Badge was too big.

Fix default Badge's font size

---

src/SegmentedButton/Segment.js
src/SegmentedButton/SegmentedButton.js
src/SegmentedButton/SegmentedButton.mdx
src/SegmentedButton/SegmentedButton.stories.js
src/SegmentedButton/__tests__/__snapshots__/index.test.js.snap
src/SegmentedButton/__tests__/index.test.js
src/SegmentedButton/index.js
src/index.js

Summary: Component allows selection from multiple options. Will be used for gender selector in passenger part of booking screen.
Related to:
https://github.com/kiwicom/margarita/issues/73
https://github.com/kiwicom/margarita/issues/121

Feat: Added SegmentedButton component

---

src/Checkbox/Checkbox.web.js
src/Checkbox/CheckboxShared.js
src/Checkbox/__tests__/__snapshots__/index.test.js.snap

Summary: 
Added `accessibilityRole` property.
Changed how `onChange` is fired in web version, so it can be now fired even by keyboard when component is in focus.
Closes: #187

Feat: CheckBox accessibility

---

src/Badge/Badge.js
src/Badge/BadgeTypes.js
src/OptionPicker/OptionPicker.js
src/OptionPicker/OptionPicker.stories.js
src/OptionPicker/OptionPickerTypes.js
src/OptionPicker/__tests__/OptionPicker.test.js
src/OptionPicker/__tests__/__snapshots__/OptionPicker.test.js.snap
src/OptionPicker/__tests__/__snapshots__/index.test.js.snap
src/OptionPicker/__tests__/index.test.js
src/OptionPicker/components/Option.js
src/OptionPicker/components/OptionList.js
src/OptionPicker/helpers.js
src/OptionPicker/index.js
src/OptionPicker/mocks/places.js
src/RowOption/RowOption.js
src/TagsInput/TagsInput.js
src/TagsInput/TagsInput.stories.js
src/TagsInput/__tests__/index.test.js
src/TagsInput/components/DeleteButton.js
src/TagsInput/components/InputField.js
src/TagsInput/components/TagsContainer.js
src/TagsInput/constants.js

Added the PlacePicker, this is not pixel perfect solution still need some iteration, but this is PR is mainly focused on functionality. 
In dev mode may appear, issue with the performance but it should work OK in build(production version)
for next iterations
- improved designs 
- improved tests
- should be moved to margarita

Add OptionPicker

---

src/LocalizedPrice/LocalizedPrice.js
src/LocalizedPrice/LocalizedPriceTypes.js

Summary: Added component web style. Style can now also be further extended with `style` prop.

Feat: Updated LocalizedPrice web styles

---

src/TextInput/TextInput.js
src/TextInput/TextInput.stories.js
src/TextInput/TextInputTypes.js
src/TextInput/__tests__/__snapshots__/index.test.js.snap

close #238 
added new options
- autoFocus
- autoCorrect

238 text input autofocus

---

.flowconfig
src/AdaptableBadge/AdaptableBadge.js
src/Icon/Icon.js
src/Icon/Icon.stories.js
src/Icon/IconTypes.js
src/Icon/__tests__/__snapshots__/index.test.js.snap
src/Icon/__tests__/index.test.js
src/Text/TextTypes.js

Summary: Improved flow typings for Text, AdaptableBadge and Icon. Prevented Icon component from crashing UI by removing error thrown; instead, we just return a question mark.

Fix: Flow typings improved

---

src/OptionPicker/OptionPicker.js
src/OptionPicker/OptionPicker.stories.js
src/OptionPicker/OptionPickerTypes.js
src/OptionPicker/__tests__/__snapshots__/OptionPicker.test.js.snap
src/OptionPicker/components/OptionList.js
src/TagsInput/TagsInput.js
src/TagsInput/TagsInput.stories.js
src/TagsInput/components/InputField.js

OptionPicker
- change ScrollView to FlatList
- fix autoFocus props
TagsInput
- unify autoFocus props
- add autoCorrect props

Improve option picker

---

src/TextInput/TextInput.js

For example, when you click on clear button in Margarita's place picker, behaviour is different than just deleting text by backspace.

Clearing value call change callback

---

src/Picker/NativePicker.js
src/Picker/Picker.ios.js
src/Picker/PickerHelpers.js
src/Picker/PickerTypes.js

Summary: Changed Picker `selectedValue` type from `string` to `?string`.

Feat: Allow Picker selectedValue to be null
