kiwicom/universal-components

- .gitignore
Update to #82 . Changed `story-loader.js` path in `.gitignore` to correct (actual) one.
> Fix: gitignore native storyloader

- src/Stepper/Stepper.js
- src/Stepper/Stepper.stories.js
- src/Stepper/__tests__/index.test.js
Fixed condition for `belowMin` and `aboveMax`. When `min` or `max` was set to zero it was always `false`.
> Fix: Stepper component disable

- package.json
- src/Button/__tests__/__snapshots__/index.test.js.snap
- src/Checkbox/CheckboxIcon.js
- src/Checkbox/__tests__/__snapshots__/index.test.js.snap
- src/FilterButton/FilterButton.js
- src/Icon/Icon.native.js
- src/Icon/Icon.stories.js
- src/Icon/Icon.web.js
- src/Icon/IconTypes.js
- src/Icon/IconsList.js
- src/Icon/__tests__/__snapshots__/index.test.js.snap
- src/Icon/__tests__/index.test.js
- src/RadioButton/RadioButton.js
- src/Stepper/Stepper.js
- src/Stepper/__tests__/__snapshots__/index.test.js.snap
- src/TextInput/TextInput.js
- yarn.lock
This is a bit hacky, but we can now see icons in the storybook for web.
To use the icon of this component library inside a web project, we would need to install `@kiwicom/orbit-components` and `styled-components` as dependencies I believe. This would need to be tested and made precise.
> Add: Icons available on Web (temporary)

- .storybook/webpack.config.js
- src/Notification/Notification.js
- src/utils/StatusBarHeight.js
- src/utils/StatusBarHeight.native.js
1. It won't be transpiled so we might have problems in projects like create-react-app
2. We do not need it
> fix: Do not use react-native-status-bar-height on web

- src/Button/Button.web.js
Closes #120.
This is ok. Just remember to use `data-test-id` on web. 
We could also write a babel plugin to enforce this or even easier... We can use https://www.npmjs.com/package/babel-plugin-jsx-remove-data-test-id and https://www.npmjs.com/package/babel-plugin-react-test-id to remove those attributes from production build.
If you would like any of the above, we can open an issue with it.
> fix: Use data-test-id instead of testID on web

- src/Button/__tests__/__snapshots__/index.test.js.snap
- src/Checkbox/__tests__/__snapshots__/index.test.js.snap
- src/Icon/Icon.js
- src/Icon/__tests__/__snapshots__/index.test.js.snap
- src/Stepper/__tests__/__snapshots__/index.test.js.snap
- src/TimelineInformation/__tests__/__snapshots__/TimelineInformation.test.js.snap
• Enhanced icon styles to make sizes and vertical centering consistent on all platforms.
• Update of impacted snapshots
Related to #136 (icon centering problem)
Before - android | ios | web
After
> Fix: Icon size is not consistent

- CONTRIBUTING.md
Summary: That PR is documenting how to properly write a commit message.
Fixes: #166
> Docs: add commit message convention

- CONTRIBUTING.md
- src/Checkbox/Checkbox.native.js
- src/Checkbox/Checkbox.web.js
- src/Checkbox/CheckboxIcon.js
- src/Checkbox/CheckboxShared.js
- src/Checkbox/CheckboxTypes.js
- src/Checkbox/Hoverable.js
Summary: CONTRIBUTING now contains guidelines on how to write flow types for components which have platform specific files; refactored the types for Checkbox component as an example of what is expected.
> docs: Added convention to write flow types

- .flowconfig
- package.json
- src/DatePicker/DatePicker.android.js
- src/DatePicker/DatePicker.ios.js
- src/DatePicker/DatePicker.stories.js
- src/DatePicker/DatePicker.web.js
- src/DatePicker/DatePickerTypes.js
- src/DatePicker/index.js
- src/index.js
- yarn.lock
Summary: For mobile we are using date pickers from `react-native` based on the native date pickers. For web we are going to use `react-datepicker` library and adjust it a bit to our requirements using prop `customInput`.
Fixes: #89
> Added: DatePicker component

- android/app/build.gradle
- android/app/src/main/java/com/storybooknative/MainApplication.java
- android/settings.gradle
- ios/storybooknative.xcodeproj/project.pbxproj
Summary: Removed `react-native-shimmer` native dependencies. Library was removed with `PlaceCard` component ( moved to `Margarita`).
Which caused build errors on both platforms when fresh `node_modules` were installed.
> Fix: Removed react-native-shimmer dependencies

- CONTRIBUTING.md
- docs/commit-template.txt
Summary: This commit template is introduced to try and improve our commit message quality; the resulting git history will be more useful and documenting. Instructions on how to set it up were added to the contributing guidelines. (I also think that commit messages should start with a capital letter, so I modified the docs to reflect that.)
> Docs: Added our commit template and instructions

- .storybook/preview-head.html
- .storybook/webpack.config.js
- package.json
- src/Icon/Icon.css
- src/Icon/Icon.css.native.js
- src/Icon/Icon.js
- yarn.lock
Summary: css-loader was used notably to load the custom `orbit-icons.ttf` font file. The NPM package provides the font and it needs to be appropriately loaded by the customer. It could be worth providing the font as a different package though.
This should be merged after the DatePicker PR is landed.
> Chore: Removed dependency over css-loader

- src/Notification/NotificationExample.js
Summary: In notification example, button didnt have a label but string wihtout text component wrapper
> FIX: Notification example button

- .circleci/config.yml
- .storybook/webpack.config.js
- package.json
- src/Slider/Marker.js
- src/Slider/Slider.js
- src/Slider/Slider.stories.js
- src/Slider/SliderParts.js
- src/Slider/index.js
- src/index.js
- yarn.lock
That PR will add slider/multislider component
Fixes: #103
> Feat: Create Slider/Multislider component

- src/DatePicker/DatePicker.android.js
- src/DatePicker/DatePicker.ios.js
- src/DatePicker/DatePicker.web.js
- src/DatePicker/DatePickerDayTile.js
- src/DatePicker/DatePickerHelpers.js
- src/DatePicker/__tests__/index.test.js
Summary:
- Set default `mode` to `date` for iOS and Android.
- Fixed bug in `web` version, when `minDate` tile was disabled in cases where time of the day was set to different value than 0.
> Fix: Unified DatePicker behavior

- src/Button/__tests__/__snapshots__/index.test.js.snap
- src/Button/styles/index.web.js
Summary: 
Removed white corners in web version (mobile versions are ok). 
It was caused by default button background color.
Solved by overriding `backgroundColor` value to `transparent`.
Before:
Default button style before override (with `buttonface` color for background):
> Fix: Button background color in web version

- README.md
Summary: Documentation will now be built whenever we push to `master`
It is available at https://kiwicom-universal-components-docs.netlify.com
> Docs: Added link to the docs in README

- src/Badge/Badge.js
- src/Badge/styles/index.js
Graphic design for badges is different than our in `universal-components'. So that is the reason for this PR. 
In the future, we need to have orbit design tokens updated because there are different badge background/text colours and height. I sent those issues to orbit team.
> Update Badge style

- src/index.js
Summary: This type is needed whenever you want to create components based off our Icon component.
> Fix: Exported IconNameType

- src/Button/ButtonInner.js
- src/TextInput/TextInput.js
Summary:
Updated `TextInput` `borderRadius` to new value according to actual designs and to be unified with `Button`.
Value for `Button` is now set from `orbit-design-tokens` but stays the same.
To prevent small inconsistencies like below while used together.
> Fix: Unified Button and TextInput border radius

- src/Button/__tests__/__snapshots__/index.test.js.snap
- src/FilterButton/__tests__/__snapshots__/index.test.js.snap
- src/Rating/__tests__/__snapshots__/index.test.js.snap
- src/Stepper/__tests__/__snapshots__/index.test.js.snap
- src/Text/Text.js
- src/Text/Text.stories.js
- src/Text/__tests__/__snapshots__/index.test.js.snap
- src/TextInput/__tests__/__snapshots__/index.test.js.snap
Summary: To extend React Native's Text component, we should allow styles to cascade. This behaviour was prevented because default values ewere set for the size, the weight and the type.
Closes #198
> Fix: Text component cascades styles

- src/RowOption/RowOptionLeftIcon.js
> Fix: fixed the RowOption arrow design on android

- README.md
- src/MenuGroup/__tests__/__snapshots__/MenuItem.android.test.js.snap
- src/MenuGroup/__tests__/__snapshots__/MenuItem.ios.test.js.snap
- src/MenuGroup/__tests__/__snapshots__/MenuItem.test.js.snap
- src/RadioButton/__tests__/__snapshots__/index.test.js.snap
- src/Stepper/__tests__/__snapshots__/index.test.js.snap
- src/Text/Text.js
- src/Text/TextTypes.js
- src/Text/__tests__/Text.android.test.js
- src/Text/__tests__/Text.ios.test.js
- src/Text/__tests__/Text.web.test.js
- src/Text/__tests__/__snapshots__/Text.android.test.js.snap
- src/Text/__tests__/__snapshots__/Text.ios.test.js.snap
- src/Text/__tests__/__snapshots__/Text.web.test.js.snap
- src/Tooltip/__tests__/__snapshots__/index.test.js.snap
Summary: Because of the way fonts are loaded in an Expo project, `fontStyle` and `fontWeight` are ignored. To make sure our Text component works in Expo apps too, an `expo` boolean prop is added to the Text component. This makes sure the right font family is used (Roboto, RobotoBold, RobotoItalic or RobotoBoldItalic) if the platform is iOS or Android and the `expo` prop is true. It also means these fonts need to be loaded (README updated).
That means that the wrapper in `margarita` will just change to have `expo` prop true by default.
> Fix: Text component is Expo compatible

- package.json
- scripts/package.json
- scripts/templates/index.js
- scripts/templates/index.native.js
Summary: Flow types were not picked up when exported as an NPM package; changing "main" and "react-native" fields in package.json to point to the right index.js files does the trick. I suspect that the previous setup was masking flow types because we were using module.exports without declaring a type for the module.
> Fix: Flow types work in host project

- src/OptionPicker/OptionPicker.js
- src/OptionPicker/OptionPicker.stories.js
- src/OptionPicker/__tests__/OptionPicker.test.js
- src/OptionPicker/__tests__/__snapshots__/OptionPicker.test.js.snap
I had to refactor the OptionalPicker from uncontrolled component to controlled component. 
As uncontrolled and stateful components it works nice but just in the storybook, If I tried implemented this in the Margarita I realized, that I need
changes the OptionalPicker's state from parents, there were two options one
use ' getDerivedStateFromProps()' but this will lead to a lot of complexity.
So I decided to change OptionalPicker to a stateless uncontrolled component.
> Refactor: change the OptionPicker from uncontrolled to controlled component

- src/CarrierLogo/CarrierLogo.js
- src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
Summary: In case of two carriers logos were aligned vertically instead of diagonally in latest version of Chrome and Firefox.
Before
After
Also reported this issue to `orbit-components` team because we are using same styling ( https://github.com/kiwicom/orbit-components/issues/821 ).
> Fix: CarrierLogo styles

- src/Picker/NativePicker.js
- src/Picker/Picker.android.js
- src/Picker/Picker.ios.js
- src/Picker/Picker.mdx
- src/Picker/Picker.stories.js
- src/Picker/Picker.web.js
- src/Picker/PickerHelpers.js
- src/Picker/PickerTypes.js
- src/Picker/__tests__/__snapshots__/index.test.js.snap
- src/Picker/__tests__/index.test.js
- src/Picker/index.js
- src/index.js
Summary: Picker implementation for each platform. Will be used for example as nationality selector in passenger section of booking screen.
Related to:
https://github.com/kiwicom/margarita/issues/73
https://github.com/kiwicom/margarita/issues/121
Desktop:
iOS:
Android:
> Feat: Added Picker component

- src/TextInput/FormLabel.js
- src/TextInput/TextInput.js
- src/TextInput/TextInputTypes.js
- src/TextInput/__tests__/__snapshots__/index.test.js.snap
Without this, I'm not able to style form labels properly, because I can change only text-related styles
> Styling prop for TextInput's label container
